GET http://localhost:5000/daftarproduks

###
GET http://localhost:5000/daftarproduks/1

###
DELETE http://localhost:5000/daftarproduks/2

###
POST http://localhost:5000/daftarproduks
Content-Type: application/json

{
    "nama" : "Produk 1",
    "harga" : 2000,
    "stok" : "3"
}

###
PATCH http://localhost:5000/daftarproduks/3
Content-Type: application/json

{
    "nama" : "Produk 2",
    "harga" : 2000,
    "stok" : "3"
}